# Generated by Django 5.0.4 on 2024-07-03 06:06

from django.db import migrations

def create_sources(apps, schema_editor):
    Source = apps.get_model('userincome', 'Source')

    sources_to_create = ["Salary", "Refunds", "Reimbursements", "Gifts"]

    for source in sources_to_create:
        Source.objects.create(name=source)


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_sources)
    ]
